INSERT INTO webprojectg18.products_in_order (order_id, product_id, quantity) VALUES (10, 1001, 1);
INSERT INTO webprojectg18.products_in_order (order_id, product_id, quantity) VALUES (10, 1021, 3);
INSERT INTO webprojectg18.products_in_order (order_id, product_id, quantity) VALUES (11, 1000, 3);
INSERT INTO webprojectg18.products_in_order (order_id, product_id, quantity) VALUES (11, 1001, 2);
INSERT INTO webprojectg18.products_in_order (order_id, product_id, quantity) VALUES (11, 1036, 2);
INSERT INTO webprojectg18.products_in_order (order_id, product_id, quantity) VALUES (12, 1000, 5);
INSERT INTO webprojectg18.products_in_order (order_id, product_id, quantity) VALUES (12, 1002, 3);
INSERT INTO webprojectg18.products_in_order (order_id, product_id, quantity) VALUES (13, 1001, 2);
INSERT INTO webprojectg18.products_in_order (order_id, product_id, quantity) VALUES (13, 1015, 3);