INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1000, 'מי ורדים', 25, null, null, null);
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1001, 'סחלב', 15, 'חלבי', null, null);
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1002, 'סחלב', 15, 'טבעוני', null, null);
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1015, 'מלבי', 10, 'חלבי', 'פסיפלורה', 'קדאיף');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1016, 'מלבי', 10, 'חלבי', 'פסיפלורה', 'קוקוס קלוי');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1017, 'מלבי', 10, 'חלבי', 'פסיפלורה', 'בוטנים מסוכרים');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1018, 'מלבי', 10, 'חלבי', 'פסיפלורה', 'בוטנים מלוחים');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1019, 'מלבי', 10, 'חלבי', 'נוטלה', 'קדאיף');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1020, 'מלבי', 10, 'חלבי', 'נוטלה', 'קוקוס קלוי');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1021, 'מלבי', 10, 'חלבי', 'נוטלה', 'בוטנים מסוכרים');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1022, 'מלבי', 10, 'חלבי', 'נוטלה', 'בוטנים מלוחים');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1023, 'מלבי', 10, 'חלבי', 'פירות יער', 'קדאיף');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1024, 'מלבי', 10, 'חלבי', 'פירות יער', 'קוקוס קלוי');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1025, 'מלבי', 10, 'חלבי', 'פירות יער', 'בוטנים מסוכרים');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1026, 'מלבי', 10, 'חלבי', 'פירות יער', 'בוטנים מלוחים');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1027, 'מלבי', 10, 'חלבי', 'פיסטוק', 'קדאיף');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1028, 'מלבי', 10, 'חלבי', 'פיסטוק', 'קוקוס קלוי');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1029, 'מלבי', 10, 'חלבי', 'פיסטוק', 'בוטנים מסוכרים');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1030, 'מלבי', 10, 'חלבי', 'פיסטוק', 'בוטנים מלוחים');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1031, 'מלבי', 10, 'חלבי', 'מי ורדים', 'קדאיף');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1032, 'מלבי', 10, 'חלבי', 'מי ורדים', 'קוקוס קלוי');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1033, 'מלבי', 10, 'חלבי', 'מי ורדים', 'בוטנים מסוכרים');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1034, 'מלבי', 10, 'חלבי', 'מי ורדים', 'בוטנים מלוחים');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1035, 'מלבי', 10, 'חלבי', 'אספרסו', 'קדאיף');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1036, 'מלבי', 10, 'חלבי', 'אספרסו', 'קוקוס קלוי');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1037, 'מלבי', 10, 'חלבי', 'אספרסו', 'בוטנים מסוכרים');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1038, 'מלבי', 10, 'חלבי', 'אספרסו', 'בוטנים מלוחים');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1039, 'מלבי', 10, 'טבעוני', 'פסיפלורה', 'קדאיף');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1040, 'מלבי', 10, 'טבעוני', 'פסיפלורה', 'קוקוס קלוי');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1041, 'מלבי', 10, 'טבעוני', 'פסיפלורה', 'בוטנים מסוכרים');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1042, 'מלבי', 10, 'טבעוני', 'פסיפלורה', 'בוטנים מלוחים');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1043, 'מלבי', 10, 'טבעוני', 'נוטלה', 'קדאיף');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1044, 'מלבי', 10, 'טבעוני', 'נוטלה', 'קוקוס קלוי');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1045, 'מלבי', 10, 'טבעוני', 'נוטלה', 'בוטנים מסוכרים');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1046, 'מלבי', 10, 'טבעוני', 'נוטלה', 'בוטנים מלוחים');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1047, 'מלבי', 10, 'טבעוני', 'פירות יער', 'קדאיף');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1048, 'מלבי', 10, 'טבעוני', 'פירות יער', 'קוקוס קלוי');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1049, 'מלבי', 10, 'טבעוני', 'פירות יער', 'בוטנים מסוכרים');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1050, 'מלבי', 10, 'טבעוני', 'פירות יער', 'בוטנים מלוחים');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1051, 'מלבי', 10, 'טבעוני', 'פיסטוק', 'קדאיף');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1052, 'מלבי', 10, 'טבעוני', 'פיסטוק', 'קוקוס קלוי');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1053, 'מלבי', 10, 'טבעוני', 'פיסטוק', 'בוטנים מסוכרים');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1054, 'מלבי', 10, 'טבעוני', 'פיסטוק', 'בוטנים מלוחים');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1055, 'מלבי', 10, 'טבעוני', 'מי ורדים', 'קדאיף');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1056, 'מלבי', 10, 'טבעוני', 'מי ורדים', 'קוקוס קלוי');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1057, 'מלבי', 10, 'טבעוני', 'מי ורדים', 'בוטנים מסוכרים');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1058, 'מלבי', 10, 'טבעוני', 'מי ורדים', 'בוטנים מלוחים');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1059, 'מלבי', 10, 'טבעוני', 'אספרסו', 'קדאיף');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1060, 'מלבי', 10, 'טבעוני', 'אספרסו', 'קוקוס קלוי');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1061, 'מלבי', 10, 'טבעוני', 'אספרסו', 'בוטנים מסוכרים');
INSERT INTO webprojectg18.products (Product_ID, Product_Name, Price, Dairy, Syrup, Topping) VALUES (1062, 'מלבי', 10, 'טבעוני', 'אספרסו', 'בוטנים מלוחים');